//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerboInves.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerboInves.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0503f4ce_a7f9_44cb_810d_375571333845_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_0503f4ce-a7f9-44cb-810d-375571333845-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _09574719_8f93_4302_b774_f9224a87c80f_removebg {
            get {
                object obj = ResourceManager.GetObject("_09574719-8f93-4302-b774-f9224a87c80f-removebg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _14eb617c_b074_477e_833a_1def6b49bd3e_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_14eb617c-b074-477e-833a-1def6b49bd3e-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3451010d_10be_4ca6_9825_ecad3bf82881_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_3451010d-10be-4ca6-9825-ecad3bf82881-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4cef6b63_53d1_4100_b6e9_04667cfaf5d4_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_4cef6b63-53d1-4100-b6e9-04667cfaf5d4-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5ab7cd1f_4910_475c_9de2_fd972571285a_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_5ab7cd1f-4910-475c-9de2-fd972571285a-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _623e18ab_f335_43d2_8824_6e98c0ed3ccf_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_623e18ab-f335-43d2-8824-6e98c0ed3ccf-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6935ef27_a4af_4c9d_849e_6f5a611d8265_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_6935ef27-a4af-4c9d-849e-6f5a611d8265-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6f12de3a_8a6e_4fb1_a885_b4699345244c_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_6f12de3a-8a6e-4fb1-a885-b4699345244c-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7a6e963d_621f_4696_b388_700b4f3c4f70_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_7a6e963d-621f-4696-b388-700b4f3c4f70-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _b2918e87_169b_4e1f_9302_7962df1ed74a_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_b2918e87-169b-4e1f-9302-7962df1ed74a-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _b2918e87_169b_4e1f_9302_7962df1ed74a_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("_b2918e87-169b-4e1f-9302-7962df1ed74a-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _b43abdc3_6b6b_4c97_b308_4848958f4888_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_b43abdc3-6b6b-4c97-b308-4848958f4888-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _b60a4560_3ddc_44da_9607_869dcb847a59_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_b60a4560-3ddc-44da-9607-869dcb847a59-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _e3c622e6_4078_46aa_a069_3627f3e6881d_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_e3c622e6-4078-46aa-a069-3627f3e6881d-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _ef91c94d_aaed_4071_8dd3_0e1a93477610 {
            get {
                object obj = ResourceManager.GetObject("_ef91c94d-aaed-4071-8dd3-0e1a93477610", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _f4f66b47_6d44_481c_85d8_f59b823536d1_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("_f4f66b47-6d44-481c-85d8-f59b823536d1-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap stylized_waves_vector_1338721_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("stylized-waves-vector-1338721-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
